name: onboarding_slider
description: On Boarding Slider Flutter 
version: 0.0.2
homepage: https://github.com/bensonarafat/onboarding_slider.git

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  freezed_annotation: ^2.4.1
  flutter_hooks: ^0.20.3
  hooks_riverpod: ^2.4.5
  build_runner: ^2.4.6
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.4.5


flutter:

